version: "2"
authtoken: 2D9dlLfwJs1jO8tIlgixgkZnuj3_5o6LBzCwzqpdjEP3tUA3f
tunnels:
  cardano:
    addr: 10003
    hostname: cardano-fuixlabs.ap.ngrok.io
    proto: http    
  docrender:
    addr: 13000
    hostname: docrender-fuixlabs.ap.ngrok.io
    proto: http
  github:
    addr: 9000 
    hostname: github-fuixlabs.ap.ngrok.io
    proto: http
  resolver:
    addr: 8000
    hostname: resolver-fuixlabs.ap.ngrok.io
    proto: http
  paperless:
    addr: 11000
    hostname: paperless-fuixlabs.ap.ngrok.io
    proto: http
  auth:
    addr: 12000
    hostname: auth-fuixlabs.ap.ngrok.io
    proto: http