version: "3.4"

services:
	cardanoservice:
		image: cardanoservice
		build:
			context: .
			dockerfile: ./Dockerfile
		environment:
			NODE_ENV: production
			TESTNET_BLOCKFROST_APIKEY: ${TESTNET_BLOCKFROST_APIKEY}
			MAINNET_BLOCKFROST_APIKEY: ${MAINNET_BLOCKFROST_APIKEY}
			PREPROD_BLOCKFROST_APIKEY: ${PREPROD_BLOCKFROST_APIKEY}
			PREVIEW_BLOCKFROST_APIKEY: ${PREVIEW_BLOCKFROST_APIKEY}
			MNEMONIC: ${MNEMONIC}
			AUTH_SERVER: ${AUTH_SERVER}
			CARDANO_NETWORK: ${CARDANO_NETWORK}
			CORS_DOMAINS: ${CORS_DOMAINS}
			CRYPTO_SECRET_PASSWORD: ${CRYPTO_SECRET_PASSWORD}
			CRYPTO_SECRET_PASSWORD_IV: ${CRYPTO_SECRET_PASSWORD_IV}
			CRYPTO_SECRET_PASSWORD_HASH: ${CRYPTO_SECRET_PASSWORD_HASH}
			DEVELOP_MNEMONIC: ${DEVELOP_MNEMONIC}
			ENVIRONMENT: ${ENVIRONMENT}
		ports:
		- 10003:10003
		- 9229:9229
		command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
