export const errorTypes = {
  COULD_NOT_FETCH_ASSET_DETAILS: "COULD_NOT_FETCH_ASSET_DETAILS",
  COULD_NOT_FETCH_MINTED_ASSETS: "COULD_NOT_FETCH_MINTED_ASSETS",
  COULD_NOT_FETCH_TRANSACTION_METADATA: "COULD_NOT_FETCH_TRANSACTION_METADATA",
  TRANSACTION_REJECT: "TRANSACTION_REJECT",
  NFT_COULD_NOT_BE_FOUND_IN_WALLET: "NFT_COULD_NOT_BE_FOUND_IN_WALLET",
  NFT_MINTED: "NFT_MINTED",
};