export const errorTypes = {
  COULD_NOT_FETCH_ASSET_DETAILS: "COULD_NOT_FETCH_ASSET_DETAILS",
  COULD_NOT_FETCH_MINTED_ASSETS: "COULD_NOT_FETCH_MINTED_ASSETS",
  COULD_NOT_FETCH_TRANSACTION_METADATA: "COULD_NOT_FETCH_TRANSACTION_METADATA",
  TRANSACTION_REJECT: "TRANSACTION_REJECT",
  NFT_COULD_NOT_BE_FOUND_IN_WALLET: "NFT_COULD_NOT_BE_FOUND_IN_WALLET",
  NFT_MINTED: "NFT_MINTED",
  ERROR_WHILE_REUSING_POLICY_ID: "ERROR_WHILE_REUSING_POLICY_ID",
  PAYLOAD_DOES_NOT_MATCH: "PAYLOAD_DOES_NOT_MATCH",
  COULD_NOT_VERIFY_BECAUSE_OF_ADDRESS_MISMATCH: "COULD_NOT_VERIFY_BECAUSE_OF_ADDRESS_MISMATCH",
};