export const errorTypes = {
  INVALID_QUERY_PARAMETERS: "INVALID_QUERY_PARAMETERS",
  INVALID_BODY: "INVALID_BODY",
  INVALID_URL: "INVALID_URL",
  COULD_NOT_FETCH_ASSET_DETAILS_OR_INVALID_NFT_METADATA: "COULD_NOT_FETCH_ASSET_DETAILS_OR_INVALID_NFT_METADATA",
  CONFIG_MISMATCH: "CONFIG_MISMATCH",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  BURN_NFT_FAILED: "BURN_NFT_FAILED",
  MISSING_ACCESS_TOKEN: "MISSING_ACCESS_TOKEN",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
};